### ISSUE TITLE
Ability to change brightness.

### ISSUE THREAD

**Issue by Avellea** [Macro-Deck-org/Macro-Deck-Client#10]
**Is your feature request related to a problem? Please describe.**
Upon opening the app, the brightness is forced to about 50%. 

**Describe the solution you'd like**
I'd like the ability to customize that, or just disable forcing a display brightness.

**Comment by SuchByte** [comment]
This feature does already exist. You can change the brightness in the device settings in the device manager.

![Screenshot_1](https://user-images.githubusercontent.com/45011179/177866529-109f880b-9e90-4fdd-b8bb-a721779a5b8e.png)
![Screenshot_2](https://user-images.githubusercontent.com/45011179/177866532-95e22989-d6a6-4584-9d5a-530ddb50e7fd.png)

**Comment by tumuyan** [comment]
I think a checkbox ( Marco Deck not change device's brightness) is needed.
Android devices always has light sensor, it could adjust the brightness better.
